# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Opx < Formula
  desc "CLI for local development at Optura"
  homepage "https://github.com/optura-ai/opx"
  version "0.0.4"
  license "Proprietary"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/optura-ai/opx/releases/download/v0.0.4/opx_0.0.4_darwin_amd64.tar.gz"
    sha256 "07fd2250e966f9b464b80356f007ed10b48d24735e5f7191dc2dde4897e95f8d"

    define_method(:install) do
      bin.install "opx"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/optura-ai/opx/releases/download/v0.0.4/opx_0.0.4_darwin_arm64.tar.gz"
    sha256 "5704652e71090062c7e8f8b60f2a5ee8d979848e1233e3d44d74e0ce9c66f635"

    define_method(:install) do
      bin.install "opx"
    end
  end

  test do
    system "#{bin}/opx", "version"
  end
end
